/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimatedPlaceholder: typeof import('./components/AnimatedPlaceholder.vue')['default']
    AsyncCityView: typeof import('./components/AsyncCityView.vue')['default']
    BaseModal: typeof import('./components/BaseModal.vue')['default']
    CityCard: typeof import('./components/CityCard.vue')['default']
    CityCardSkeleton: typeof import('./components/CityCardSkeleton.vue')['default']
    CityList: typeof import('./components/CityList.vue')['default']
    CityViewSkeleton: typeof import('./components/CityViewSkeleton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteNavigation: typeof import('./components/SiteNavigation.vue')['default']
  }
}
